export enum ImportColumns {
  ORDER_NUM = "מספר הזמנה",
  ORDER_DATE = "תאריך הזמנה",
  ORDER_STATUS = "סטטוס הזמנה",
  COSTUMER_NAME = "השם הפרטי של הלקוח",
  COSTUMER_LAST_NAME = "שם המשפחה של הלקוח",
  COSTUMER_TELEPHONE = "טלפון הלקוח",
  EMAIL = "מייל",
  PRODUCT_NAME = "שם המוצר",
  QUANTITY = "כמות",
  PRIVE_INC_TAX = "סה״כ כולל מע״מ",
  CURRENCY = "מטבע",
  SHIPMENT_TYPE = "אופן המשלוח",
  ADDRESS = "כתובת המשלוח",
  CITY = "עיר",
  TELEPHONE_SHIPPING = "טלפון המשלוח",
  TEXT_ORDER = "הערה להזמנה",
  TEXT_SHIPMENT = "הערה למשלוח",
  INTERNAL_COMMENT = "הערה פנימית",
}

export enum ExportColumns {
  TYPE = "רשומה",
  COSTUMER_NUM = "מס.לקוח",
  COSTUMER_NAME = "שם לקוח",
  ORDER_DATE = "תאריך הזמנה",
  ORDER_NUM = "מס.הזמנה",
  DETAILS = "פרטים",
  ID = "מקט",
  DESCRIPTION = "תיאור",
  QUANTITY = "כמות",
  PRICE_BEFORE_TAX = "מחיר לפני מעמ",
  COSTUMER_CONTACT = "איש קשר",
  TELEPHONE_NUM = "טלפון",
  EMAIL = "אימייל",
  ADDRESS1 = "כתובת 1",
  ADDRESS2 = "כתובת 2",
  ADDRESS3 = "כתובת 3",
  CITY = "עיר",
  TEXT = "טקסט להזמנה"
}